### ISSUE TITLE
Pixiv login is broken

### ISSUE THREAD

**Issue by VeryEvilHumna** [mvdicarlo/postybirb-plus#150]
![изображение](https://user-images.githubusercontent.com/90103432/221110811-d468e74b-2363-4cf7-a89a-72c9c34e7eb6.png)
![изображение](https://user-images.githubusercontent.com/90103432/221110872-a0916b93-2c06-41e8-acfb-81fedda1542c.png)
![изображение](https://user-images.githubusercontent.com/90103432/221111134-395759a6-d559-4720-8fb5-f6fa7b626a15.png)

same with not plus version.

**Comment by VeryEvilHumna** [comment]
forgot to provide the logs

```{"message":"[NestApplication] Nest application successfully started","level":"info","timestamp":"2023-04-18T19:27:42.995Z"}
{"message":"[https://www.pixiv.net] read ECONNRESET Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)","level":"error","timestamp":"2023-04-18T19:27:45.407Z"}
{"message":"[Pixiv Login Check Failure] Cannot read properties of undefined (reading 'includes') TypeError: Cannot read properties of undefined (reading 'includes')\n    at Pixiv.checkLoginStatus (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\websites\\pixiv\\pixiv.service.js:40:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async AccountService.checkLogin (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\account\\account.service.js:158:24)\n    at async Promise.all (index 2)","level":"error","timestamp":"2023-04-18T19:27:45.409Z"}
{"message":"Checking for update","level":"info","timestamp":"2023-04-18T19:27:47.690Z"}
{"message":"[UpdateService] Checking for update...","level":"info","timestamp":"2023-04-18T19:27:47.692Z"}
{"message":"Update for version 3.1.16 is not available (latest version: 3.1.16, downgrade is disallowed).","level":"info","timestamp":"2023-04-18T19:27:50.493Z"}
{"message":"[Delete Account] FurAffinity-1677222042324","level":"info","timestamp":"2023-04-18T19:28:03.834Z"}
{"message":"[Remove All Parts For Account] FurAffinity-1677222042324","level":"info","timestamp":"2023-04-18T19:28:03.924Z"}
{"message":"[Delete Submission Template Parts For Account] FurAffinity-1677222042324","level":"info","timestamp":"2023-04-18T19:28:03.925Z"}
{"message":"[Delete Account] Pixiv-1677222158055","level":"info","timestamp":"2023-04-18T19:28:09.130Z"}
{"message":"[Remove All Parts For Account] Pixiv-1677222158055","level":"info","timestamp":"2023-04-18T19:28:09.136Z"}
{"message":"[Delete Submission Template Parts For Account] Pixiv-1677222158055","level":"info","timestamp":"2023-04-18T19:28:09.137Z"}
{"message":"[Create Account] {\n \"_id\": \"Pixiv-REDACTED\",\n \"website\": \"Pixiv\",\n \"alias\": \"REDACTED\"\n}","level":"info","timestamp":"2023-04-18T19:28:14.789Z"}
{"message":"[https://www.pixiv.net] read ECONNRESET Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)","level":"error","timestamp":"2023-04-18T19:30:33.761Z"}
{"message":"[Pixiv Login Check Failure] Cannot read properties of undefined (reading 'includes') TypeError: Cannot read properties of undefined (reading 'includes')\n    at Pixiv.checkLoginStatus (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\websites\\pixiv\\pixiv.service.js:40:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async AccountService.checkLogin (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\account\\account.service.js:158:24)","level":"error","timestamp":"2023-04-18T19:30:33.763Z"}
{"message":"[https://www.pixiv.net] read ECONNRESET Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)","level":"error","timestamp":"2023-04-18T19:34:41.066Z"}
{"message":"[Pixiv Login Check Failure] Cannot read properties of undefined (reading 'includes') TypeError: Cannot read properties of undefined (reading 'includes')\n    at Pixiv.checkLoginStatus (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\websites\\pixiv\\pixiv.service.js:40:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async AccountService.checkLogin (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\account\\account.service.js:158:24)","level":"error","timestamp":"2023-04-18T19:34:41.067Z"}
{"message":"[NestApplication] Nest application successfully started","level":"info","timestamp":"2023-04-18T19:35:17.313Z"}
{"message":"[https://www.pixiv.net] read ECONNRESET Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)","level":"error","timestamp":"2023-04-18T19:35:18.977Z"}
{"message":"[Pixiv Login Check Failure] Cannot read properties of undefined (reading 'includes') TypeError: Cannot read properties of undefined (reading 'includes')\n    at Pixiv.checkLoginStatus (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\websites\\pixiv\\pixiv.service.js:40:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async AccountService.checkLogin (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\account\\account.service.js:158:24)\n    at async Promise.all (index 1)","level":"error","timestamp":"2023-04-18T19:35:19.005Z"}
{"message":"Checking for update","level":"info","timestamp":"2023-04-18T19:35:22.033Z"}
{"message":"[UpdateService] Checking for update...","level":"info","timestamp":"2023-04-18T19:35:22.034Z"}
{"message":"Update for version 3.1.16 is not available (latest version: 3.1.16, downgrade is disallowed).","level":"info","timestamp":"2023-04-18T19:35:24.644Z"}
{"message":"[NestApplication] Nest application successfully started","level":"info","timestamp":"2023-04-18T19:36:30.024Z"}
{"message":"[https://www.pixiv.net] read ECONNRESET Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)","level":"error","timestamp":"2023-04-18T19:36:33.048Z"}
{"message":"[Pixiv Login Check Failure] Cannot read properties of undefined (reading 'includes') TypeError: Cannot read properties of undefined (reading 'includes')\n    at Pixiv.checkLoginStatus (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\websites\\pixiv\\pixiv.service.js:40:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async AccountService.checkLogin (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\account\\account.service.js:158:24)\n    at async Promise.all (index 1)","level":"error","timestamp":"2023-04-18T19:36:33.054Z"}
{"message":"[Unhandled Rejection] ERR_FAILED (-2) loading 'file:///%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\build\\index.html' Error: ERR_FAILED (-2) loading 'file:///%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\build\\index.html'\n    at rejectAndCleanup (node:electron/js2c/browser_init:161:7647)\n    at EventEmitter.stopLoadingListener (node:electron/js2c/browser_init:161:8022)\n    at EventEmitter.emit (node:events:526:28)","level":"error","timestamp":"2023-04-18T19:36:33.694Z"}
{"message":"Checking for update","level":"info","timestamp":"2023-04-18T19:36:34.529Z"}
{"message":"[UpdateService] Checking for update...","level":"info","timestamp":"2023-04-18T19:36:34.530Z"}
{"message":"Update for version 3.1.16 is not available (latest version: 3.1.16, downgrade is disallowed).","level":"info","timestamp":"2023-04-18T19:36:36.346Z"}
{"message":"[NestApplication] Nest application successfully started","level":"info","timestamp":"2023-04-18T19:37:08.393Z"}
{"message":"[https://www.pixiv.net] read ECONNRESET Error: read ECONNRESET\n    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)","level":"error","timestamp":"2023-04-18T19:37:08.855Z"}
{"message":"[Pixiv Login Check Failure] Cannot read properties of undefined (reading 'includes') TypeError: Cannot read properties of undefined (reading 'includes')\n    at Pixiv.checkLoginStatus (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\websites\\pixiv\\pixiv.service.js:40:32)\n    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async AccountService.checkLogin (%temp%\\2O7xCd1C8zdYy5ipeMtgfO7DLv6\\resources\\app.asar\\dist\\server\\account\\account.service.js:158:24)\n    at async Promise.all (index 1)","level":"error","timestamp":"2023-04-18T19:37:08.856Z"}
{"message":"Checking for update","level":"info","timestamp":"2023-04-18T19:37:13.132Z"}
{"message":"[UpdateService] Checking for update...","level":"info","timestamp":"2023-04-18T19:37:13.134Z"}
{"message":"Update for version 3.1.16 is not available (latest version: 3.1.16, downgrade is disallowed).","level":"info","timestamp":"2023-04-18T19:37:14.520Z"}
```

**Comment by mvdicarlo** [comment]
Still an issue?
