### ISSUE TITLE
Error Scheluding and Posting, Infinite ETA

### ISSUE THREAD

**Issue by EmiTo-7** [mvdicarlo/postybirb-plus#346]
Hello, i have an issue posting with the program, used to work before but back then it just broke up, i got a new pc, installed it here and its still broken

What is happening is that once you schelude or "post it" it would say "will post at XX:XX:XX" ETERNALLY, it would refuse to post at  the indicated date
If you schelude, it would just do the same, pass from schelude to posting and put the ETA to the current date but without posting at all
I have waited to see if it has a delay and will post later on but after a day without doing anything i gave up
![Screenshot 2024-07-15 152243](https://github.com/user-attachments/assets/f54cb0d1-3a62-4afb-8d3f-c837e4af8d77)

**Comment by mvdicarlo** [comment]
Could you provide the logs folder (zipped)?
You can find it at %appdata%/postybirb-plus

It sounds like a strange file saving issue potentially but hard to say without the logs.
And do you use OneDrive for your documents folder?

**Comment by EmiTo-7** [comment]
[app-2024-07-15.log](https://github.com/user-attachments/files/16265591/app-2024-07-15.log)
[log-audit.json](https://github.com/user-attachments/files/16265592/log-audit.json)
here they are!

and no, my files are saved in a normal folder in my ssd
i let the program running for a few hours with that error "running" so hopefully you find something, thank you for replying!

**Comment by mvdicarlo** [comment]
I need to remind myself on how the app queues everything since it has been a few years since I reviewed that code.

But in the logs at a glance the only thing that I am noticing as strange is an error here that happens during posting.
So it might be that something like the resize functionality is having issue with a file.

I might be able to try to reproduce it if you send me the file you are getting stuck with and the list of websites you are trying to post to as I am unsure if it is an issue with the file itself or a website interaction. It has been a few years but it wouldn't be the first time some weirdness with files happened.

{"message":"[FileManagerService] Could not find MIME for Buffer <null> Error: Could not find MIME for Buffer <null>\n    at Jimp.parseBitmap$ (C:\\Users\\vasqu\\AppData\\Local\\Programs\\postybirb-plus\\resources\\app.asar\\node_modules\\@jimp\\core\\dist\\utils\\image-bitmap.js:224:48)\n    at tryCatch (C:\\Users\\vasqu\\AppData\\Local\\Programs\\postybirb-plus\\resources\\app.asar\\node_modules\\regenerator-runtime\\runtime.js:63:40)\n    at Generator.invoke [as _invoke] (C:\\Users\\vasqu\\AppData\\Local\\Programs\\postybirb-plus\\resources\\app.asar\\node_modules\\regenerator-runtime\\runtime.js:293:22)\n    at Generator.next (C:\\Users\\vasqu\\AppData\\Local\\Programs\\postybirb-plus\\resources\\app.asar\\node_modules\\regenerator-runtime\\runtime.js:118:21)\n    at tryCatch (C:\\Users\\vasqu\\AppData\\Local\\Programs\\postybirb-plus\\resources\\app.asar\\node_modules\\regenerator-runtime\\runtime.js:63:40)\n    at invoke (C:\\Users\\vasqu\\AppData\\Local\\Programs\\postybirb-plus\\resources\\app.asar\\node_modules\\regenerator-runtime\\runtime.js:154:20)\n    at C:\\Users\\vasqu\\AppData\\Local\\Programs\\postybirb-plus\\resources\\app.asar\\node_modules\\regenerator-runtime\\runtime.js:164:13","level":"error","timestamp":"2024-07-15T18:17:16.761Z"}

**Comment by EmiTo-7** [comment]
sure! be mindful its a nsfw file hehe
so...
- Inkbunny
- Bluesky
- Itaku
- e621

Here is how it happened, used to live with a low internet connection, doesnt go well with inkbunny multifile uploads
multiple times i've had to reupload to inkbunny just because postybird missed few files or what i call a half complete upload (uploads all pictures but it denies it and puts it as hidden without putting the tags or info)
i was uploading a batch of pictures without issues, but suddenly it just didnt wanted to cooperate, mid upload it manage to upload 2 of 6 pictures 2 of them uploaded to e621 and itaku, inkbunny denied the upload and then i stopped the rest of the pictures, tried to upload the batch of 6 pics to inkbunny and the bug happened

i got a new computer, transfer my doc to this one and i presume thats where postybird old data is cus it could recognize my accounts, still this issue keeps happening, maybe i could delete those files and things could be fixed

Here are the 7 files (forgot there was another one) maybe there is an issue it could be fixed but be mindful, all these pictures are nsfw and kinky

![Damon C3 piss inner](https://github.com/user-attachments/assets/27489820-cf27-40e1-a1d0-589a5292b925)
![Damon C3 piss](https://github.com/user-attachments/assets/2163ee9f-0381-465b-b823-389547ad2e61)
![Damon C3](https://github.com/user-attachments/assets/ab9504b6-61f5-4d4e-b9d8-94502f9bbad5)
![Damon C3 cum inner](https://github.com/user-attachments/assets/297766a3-163a-47dc-9d60-9adbc2331f52)
![Damon C3 cum](https://github.com/user-attachments/assets/cbe562ab-9501-49a4-90b8-2790e1ee52ee)
![Damon C3 eggs inner](https://github.com/user-attachments/assets/857cba8e-63dd-4416-9be4-ec864b041790)
![Damon C3 eggs](https://github.com/user-attachments/assets/5137a00b-c6cc-414c-bf54-359b69be7971)

**Comment by mvdicarlo** [comment]
Apologies, I should have offered an alternative to posting it here. I hope you don't mind I deleted your comment for the sake of not potentially running into issues with github content policies. It would be better if you emailed them to me or reached out on discord. I don't mind files like that personally, more of just a precaution.

**Comment by EmiTo-7** [comment]
Eep, didn't consider that, my bad too
Sure, discord is fine, my code is
emito_rawr

**Comment by mvdicarlo** [comment]
I believe this was resolved.
